[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 1000

[invariant]
runs = 20
depth = 1000
shrink_run_limit = 100
fail_on_revert = true

[profile.pr.invariant]
runs = 200
depth = 1000
shrink_run_limit = 50_000

[profile.pr.fuzz]
runs = 100_000

[profile.master.invariant]
runs = 250
depth = 2500
shrink_run_limit = 50_000

[profile.master.fuzz]
runs = 1_000_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

remappings = [
    "ds-test/=lib/erc20-helpers/lib/forge-std/lib/ds-test/src/",
    "erc20-helpers/=lib/erc20-helpers/src/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${OPTIMISMSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
gnosis_chain = { key = "${GNOSISSCAN_API_KEY}", url = "https://api.gnosisscan.io/api" }
arbitrum_one = { key = "${ARBISCAN_API_KEY}" }
world_chain = { key = "${WORLD_CHAIN_API_KEY}", chain = 480, url = "https://worldchain-mainnet-explorer.alchemy.com/api" }
unichain = { key = "${UNICHAIN_API_KEY}", chain = 130, url = "https://unichain.blockscout.com/api" }
